use_frameworks!

target 'PodTest_Example' do
  pod 'LJPodTestwzt', :path => ‘../0.1.0/’
  pod 'AFNetworking'

  target 'PodTest_Tests' do
    inherit! :search_paths


  end
end


target 'PodTestBinary' do
    
end
