# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'podtest111' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for podtest111
    pod 'AFNetworking'
    
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['USER_HEADER_SEARCH_PATHS'] = '${PODS_ROOT}/**'
                end
            end
        end
    end
end


